// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:itollet/utils/timestamp_serializer.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'customer_register_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'customer_register_model.g.dart';

@freezed
class CustomerRegisterModel with _$CustomerRegisterModel {
  const factory CustomerRegisterModel({
    required String? email,
    required String? password,
    required String? rePassword
    
    



  }) = _CustomerRegisterModel;

  factory CustomerRegisterModel.fromJson(Map<String, Object?> json) => _$CustomerRegisterModelFromJson(json);
}