// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:itollet/utils/timestamp_serializer.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'sales_register_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'sales_register_model.g.dart';

@freezed
class SalesRegisterModel with _$SalesRegisterModel {
  const factory SalesRegisterModel({
    required String? email,
    required String? companyName,
    required String? companyPhone,
    required String? password,
    required String? rePassword,

    
    
    @TimestampSerializer() required DateTime? createdAt,



  }) = _SalesRegisterModel;

  factory SalesRegisterModel.fromJson(Map<String, Object?> json) => _$SalesRegisterModelFromJson(json);
}