// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:itollet/features/Account/Utils/account_transaction_type_enum.dart';
import 'package:itollet/features/Account/Utils/account_transaction_type_seriliazer.dart';
import 'package:itollet/utils/timestamp_serializer.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'account_transaction_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'account_transaction_model.g.dart';

@freezed
class AccountTransactionModel with _$AccountTransactionModel {
  const factory AccountTransactionModel({
    required String? amount,
    required String fromUid,
    @TimestampSerializer() required DateTime createdAt,
    required String docId,
    @AccountTransactionTypeSerializer() required AccountTransactionTypes type,
  }) = _AccountTransactionModel;

  factory AccountTransactionModel.fromJson(Map<String, Object?> json) =>
      _$AccountTransactionModelFromJson(json);
}
