// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:itollet/utils/timestamp_serializer.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'user_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_model.g.dart';

@freezed
class UserModel with _$UserModel {
  const factory UserModel({
    required String? uid,
    required String? userName,
    required String? email,
    required double? balance,
    @TimestampSerializer() required DateTime? createdAt,
    required String? photoUrl,
  }) = _UserModel;

  factory UserModel.fromJson(Map<String, Object?> json) => _$UserModelFromJson(json);
}
